require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => :spec

task :spec do
	#sh "ruby -I spec/Alimento_spec.rb"
        sh "ruby -I spec/aigb_spec.rb"
end
